# Generated by Django 4.1.7 on 2023-06-27 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=20)),
                ("number", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=20)),
                ("experiance", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("cpassword", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=20)),
                ("fordate", models.CharField(max_length=20)),
                ("fromtime", models.CharField(max_length=10)),
                ("totime", models.CharField(max_length=10)),
                ("num", models.IntegerField()),
                ("tablemembers", models.IntegerField()),
                ("address", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="outsideuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=20)),
                ("num", models.IntegerField()),
                ("address", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=20)),
                ("cpassword", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=10)),
                ("role", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="chef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=20)),
                ("number", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=20)),
                ("experiance", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("cpassword", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
